# Generated by Django 4.2.4 on 2023-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_telegram_id_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.IntegerField(blank=True, null=True, verbose_name='telegram id'),
        ),
    ]
