# Generated by Django 4.2.4 on 2023-08-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='nice_habit',
            field=models.ManyToManyField(to='habits.nicehabit', verbose_name='приятная привычка'),
        ),
    ]
