# Generated by Django 4.2.4 on 2023-08-21 00:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_nice_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)], verbose_name='периодичность'),
        ),
        migrations.RemoveField(
            model_name='habit',
            name='nice_habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='nice_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.nicehabit', verbose_name='приятная привычка'),
        ),
    ]
