# Generated by Django 4.2.4 on 2023-08-21 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_period_remove_habit_nice_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='durations',
            field=models.SmallIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)], verbose_name='продолжительность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)], verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='nicehabit',
            name='durations',
            field=models.SmallIntegerField(default=120, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)], verbose_name='продолжительность'),
        ),
    ]
