# Generated by Django 4.2.4 on 2023-08-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_durations_alter_habit_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicehabit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='публичная'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(max_length=100, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='nicehabit',
            name='action',
            field=models.CharField(max_length=100, verbose_name='действие'),
        ),
    ]
