# Generated by Django 4.2.4 on 2023-08-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_habit_habits_habit_reward_or_nice_habit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='habits_habit_reward_or_nice_habit',
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('nice_habit__isnull', False), ('reward__isnull', True)), models.Q(('nice_habit__isnull', True), ('reward__isnull', False)), models.Q(('nice_habit__isnull', True), ('reward__isnull', True)), _connector='OR'), name='habits_habit_reward_or_nice_habit'),
        ),
    ]
