# Generated by Django 4.2.4 on 2023-08-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_remove_habit_habits_habit_reward_or_nice_habit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='habits_habit_reward_or_nice_habit',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='period',
        ),
    ]
