# Generated by Django 4.2.4 on 2023-08-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_remove_habit_habits_habit_reward_or_nice_habit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.CharField(default='1234567', verbose_name='периодичность'),
        ),
    ]
