# Generated by Django 4.2.4 on 2023-08-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(default='1234567', max_length=7, verbose_name='периодичность'),
        ),
    ]
