# Generated by Django 4.2.4 on 2023-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_alter_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicehabit',
            name='period',
            field=models.CharField(default='1234567', max_length=7, verbose_name='периодичность'),
        ),
    ]
